name: Add CVE Label
on:
  issues:
    types:
      - labeled

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  add-comment:
    if: github.event.label.name == "Mend: dependency security vulnerability"
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Title
        id: get_title
        run: |
          issue_title="${{ github.event.issue.title }}"
          severity="$(echo $issue_title | sed -n 's/.*(\(.*\)).*/\1/p')"
          echo "severity=$severity" >> $GITHUB_ENV
      - name: Add CVE Label
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ github.event.issue.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ${{ env.severity }}
            })