name: Test PR Author
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-pr-author:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log PR Author
        run: echo "This pull request was created by ${{ github.event.pull_request.user.login }}"
